services:
  postgres:
    image: postgres:16
    container_name: digital-bank
    environment:
      # fullURL = jdbc:postgresql://localhost:5433/digital_bank
      POSTGRES_DB: digital_bank
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    volumes:
      - digital_bank_data:/var/lib/postgresql/data

volumes:
  digital_bank_data: